# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: releaser-test

env:
  - GO111MODULE=on

before:
  hooks:
    - "go mod download"


builds:
  -
    binary: releaser-test
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  -
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - dockerfile: Dockerfile
    binaries:
      - releaser-test
    image_templates:
      - "arekkas/releaser-test:v{{ .Major }}"
      - "arekkas/releaser-test:v{{ .Major }}.{{ .Minor }}"
      - "arekkas/releaser-test:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "arekkas/releaser-test:{{ .Env.DOCKER_SHORT_TAG }}"
      - "arekkas/releaser-test:latest"

release:
  prerelease: auto
  name_template: "{{.Env.RELEASE_NAME}}"
